/**
 * Created by sjwjames on 16/3/16.
 */
var Constants={
  mirrors:[
      [
      {x:0.2,y:cc.director.getVisibleSize().height/3*2,angle:0,type:2},
      {x:0.4,y:cc.director.getVisibleSize().height/3*2,angle:0,type:2},
      {x:0.6,y:cc.director.getVisibleSize().height/3*2,angle:0,type:2},
      {x:0.2,y:cc.director.getVisibleSize().height/3,angle:0,type:3},
      {x:0.4,y:cc.director.getVisibleSize().height/3,angle:0,type:3},
      {x:0.6,y:cc.director.getVisibleSize().height/3,angle:0,type:3}
     ],
      [
          {x:0,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:100,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:200,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:0,y:cc.director.getVisibleSize().height/2,angle:0,type:1},
          {x:100,y:cc.director.getVisibleSize().height/2,angle:0,type:1},
          {x:200,y:cc.director.getVisibleSize().height/2,angle:0,type:1}
      ],
      [
          {x:0,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:100,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:200,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:0,y:cc.director.getVisibleSize().height/2,angle:0,type:1},
          {x:100,y:cc.director.getVisibleSize().height/2,angle:0,type:1},
          {x:200,y:cc.director.getVisibleSize().height/2,angle:0,type:1}
      ],
      [
          {x:0,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:100,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:200,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:0,y:cc.director.getVisibleSize().height/2,angle:0,type:1},
          {x:100,y:cc.director.getVisibleSize().height/2,angle:0,type:1},
          {x:200,y:cc.director.getVisibleSize().height/2,angle:0,type:1}
      ],
      [
          {x:0,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:100,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:200,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:0,y:cc.director.getVisibleSize().height/2,angle:0,type:1},
          {x:100,y:cc.director.getVisibleSize().height/2,angle:0,type:1},
          {x:200,y:cc.director.getVisibleSize().height/2,angle:0,type:1}
      ],
      [
          {x:0,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:100,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:200,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:0,y:cc.director.getVisibleSize().height/2,angle:0,type:1},
          {x:100,y:cc.director.getVisibleSize().height/2,angle:0,type:1},
          {x:200,y:cc.director.getVisibleSize().height/2,angle:0,type:1}
      ],
      [
          {x:0,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:100,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:200,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:0,y:cc.director.getVisibleSize().height/2,angle:0,type:1},
          {x:100,y:cc.director.getVisibleSize().height/2,angle:0,type:1},
          {x:200,y:cc.director.getVisibleSize().height/2,angle:0,type:1}
      ],
      [
          {x:0,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:100,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:200,y:cc.director.getVisibleSize().height/3*2,angle:0,type:1},
          {x:0,y:cc.director.getVisibleSize().height/2,angle:0,type:1},
          {x:100,y:cc.director.getVisibleSize().height/2,angle:0,type:1},
          {x:200,y:cc.director.getVisibleSize().height/2,angle:0,type:1}
      ]

  ]
};